### ISSUE TITLE
Ambiguous reference to member 'write(_:value:type:result:)'

### ISSUE THREAD

**Issue by LeeCenY** [MoveUpwards/Gormsson#16]
The following code will give an error like this
```swift
manager?.write(GPSControl(), value: GPSControlEnum.start, type: .withResponse) { result in
            switch result {
            case .success(let value):
                print("GPSControl stop:", value as? GPSControlEnum ?? "nil")
            case .failure(let error):
                print("GPSControl stop error:", error)
            }
        }
```
![image](https://user-images.githubusercontent.com/9047094/59692976-ae245d80-9218-11e9-9c07-ce63139f9a2c.png)

**Comment by damien-nd** [comment]
Do you try to compile GormssonDemo? And you modify the code in DetailViewController line 130?

**Comment by LeeCenY** [comment]
![image](https://user-images.githubusercontent.com/9047094/59698004-66ee9a80-9221-11e9-9269-d4f2718c73ae.png)
The demo is not going to give up such an error, it appears in my project, I will study it again to see where I am wrong.

**Comment by damien-nd** [comment]
As I can see, you may have use GPSControl class but change the format to UInt8?
It works as both for me. Maybe try to use `GPSControlEnum.start.rawValue` or if you can give your changes in GPSControl to try to help you.

**Comment by LeeCenY** [comment]
```GPSControlEnum.start.rawValue```  This can be solved, Thank

**Comment by damien-nd** [comment]
I'm happy we fix this one, so let's fix the second one ;)
