### ISSUE TITLE
Listening device away from disconnect callback method

### ISSUE THREAD

**Issue by LeeCenY** [MoveUpwards/Gormsson#21]
Listening device away from disconnect callback method
```swift
didDisconnectPeripheral
```

**Comment by damien-nd** [comment]
Hi @LeeCenY 

What is your issue?

When CBCentralManager trigger `didDisconnectPeripheral `, Gormsson will trigger the `didDisconnectHandler ` you set on connect function or later via a set function.

**Comment by LeeCenY** [comment]
Hi @damien-nd 
Suggested to add when the device is disconnected, there is a way to call back to us

**Comment by LeeCenY** [comment]
@damien-nd Thank you, I found that the new version already provides such a method.

**Comment by LeeCenY** [comment]
It is recommended to update the documentation

**Comment by damien-nd** [comment]
I forget when we add it but I will add it to the documentation. Good catch.
